name: Manual Deploy Application

on:
    workflow_dispatch:

jobs:
    deploy-frontend:
        name: Deploy Frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Dependencies and Build
              working-directory: ./frontend
              run: |
                  npm ci
                  npm run build

            - name: Deploy to S3
              run: |
                  aws s3 sync ./build s3://$S3_BUCKET --delete
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: "us-east-1"
                  S3_BUCKET: ${{ secrets.S3_BUCKET }}

    deploy-backend:
        name: Deploy Backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script: |
                      cd /backend
                      git pull origin main
                      pm2 restart all
